left_theme:
  default: 1
  description: "Enter a Theme id here. To find the Theme ID, click your theme name in admin > customize > themes. The ID is the last number in the URL."
right_theme:
  default: 2
